//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportDispatcher.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flights()
        {
            this.TicketFlights = new HashSet<TicketFlights>();
        }
    
        public int FlightID { get; set; }
        public string FlightNo { get; set; }
        public Nullable<long> ScheduledDeparture { get; set; }
        public Nullable<long> ScheduledArrival { get; set; }
        public string DepartureAirport { get; set; }
        public string ArrivalAirport { get; set; }
        public string Status { get; set; }
        public string AircraftCode { get; set; }
        public Nullable<long> ActualDeparture { get; set; }
        public Nullable<long> ActualArrival { get; set; }
    
        public virtual Aircrafts Aircrafts { get; set; }
        public virtual Airports Airports { get; set; }
        public virtual Airports Airports1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketFlights> TicketFlights { get; set; }
    }
}
